spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1nmqv1berdt93zu9o.mysql.rds.aliyuncs.com:3306/ishopping
    username: root
    password: Hellosyman1
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoyuan.demo.mysql.random.mapper
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      db-type: mysql