server:
  port: 8080

spring:
  application:
    name: cache-redis-server
  redis:
    host: 11.11.11.111
    port: 6379
    database: 2
#    database: 66
#    timeout: 3000
#    password: test

#    sentinel: #哨兵模式
#      master: mymaster #主服务器所在集群名称
#      nodes: 11.11.11.111:6379,11.11.11.112:6379,11.11.11.113:6379

#    cluster:
#      nodes: 11.11.11.111:6379,11.11.11.112:6379,11.11.11.113:6379,11.11.11.114:6379,11.11.11.115:6379,11.11.11.116:6379,11.11.11.117:6379,11.11.11.118:6379,11.11.11.119:6379
#    lettuce:
#      pool:
#        max-idle: 50
#        min-idle: 10
#        max-active: 100
#        max-wait: 1000

